### PR TITLE
seperate seed generation for zkey contribute deterministic

### PR DESCRIPTION
**Pull request by jacobrosenthal**
Im working with the Dark Forest folks on some toolchain stuff and were looking at making dev builds deterministic. Any thoughts on a patch like this. Some code duplication yet, and willing to bikeshed naming of course.

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
zkey_contributed is just a copy of the upstream file copied and this line deleted
https://github.com/iden3/snarkjs/blob/master/src/zkey_contribute.js#L24

If its a good change we could simply add seed as an optional param to the existing zkey_contribute function

**Comment by jbaylina** [comment]
You can use `zkey beacon` to do a deterministic contribution.

**Comment by jacobrosenthal** [comment]
I think that indeed does it. Thanks!

**Comment by jacobrosenthal** [comment]
Though beaconhash generation in hex isnt exposed I dont think? Would you recommend a random uuid generation from some os util? or is it worth to expose that?

**Pull request closed without merging**
