### PR TITLE
fix(cli): Correctly return status codes instead of values

### LINKED ISSUE #366: Error occurred while starting a new powers of tau ceremony
I installed snarkjs by npm
```bash
npm i -g snarkjs
```
I got an error while starting a new powers of tau ceremony.
```bash
snarkjs powersoftau new bn128 14 pot12_0000.ptau -v
```

Here's the error message:
```bash
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received an instance of Uint8Array
    at process.set [as exitCode] (node:internal/bootstrap/node:124:9)
    at process.exit (node:internal/process/per_thread:188:24)
    at /Users/chentihe/.nvm/versions/node/v20.1.0/lib/node_modules/snarkjs/build/cli.cjs:12550:13 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### PR DESCRIPTION
**Pull request by phated**
Fixes #366

This fixes usage of various commands in the CLI. Generally, we want to avoid returning function calls because they return values that might be used in application code; however the CLI expect integers to be returned so it can call `process.exit(code)`.

@chentihe please try this code and see if it works.

### CODE REVIEW

**Comment by chentihe** [comment]
Hi @phated ,

Thanks for your quick reply, I just test with this branch, and there's no error message occurred!

image

**Comment by FoodChain1028** [comment]
Hi, @chentihe it seemed like you've solved your problem. I encounter the same issue and cannot execute my snarkjs and could not find where cli.js is. could you help me with this?

**Comment by phated** [comment]
@chentihe thanks for the test, I've merged this and will ask Jordi to make an official release.

**Comment by chentihe** [comment]
Hi @FoodChain1028 

For now, you can just ignore the error, snarkjs cli still works, you can wait for the official release to upgrade the version of snarkjs.

**Comment by FoodChain1028** [comment]
Hi @chentihe  
Thank you for answering 🙂

**Pull request merged**
